"""Daily knowledge capture: search topics and persist a markdown digest.

Writes memory/YYYY-MM-DD.md (append-safe per day) and a journal entry.
Tests inject FixtureAdapter so nothing hits the network.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date, datetime, timezone
from pathlib import Path

from core.memory import Journal, MemoryEntry
from tools.research import Hit, SearchAdapter, format_hits, search, summarize

DEFAULT_TOPICS = (
    "personal knowledge management",
    "autonomous software agents",
)


@dataclass
class CaptureResult:
    day: str
    path: Path
    topics: list[str]
    hit_count: int
    markdown: str
    hits_by_topic: dict[str, list[Hit]] = field(default_factory=dict)


def _utc_day(when: datetime | None = None) -> str:
    stamp = when or datetime.now(timezone.utc)
    return stamp.strftime("%Y-%m-%d")


def render_digest(day: str, hits_by_topic: dict[str, list[Hit]]) -> str:
    lines = [
        f"# Knowledge capture — {day}",
        "",
        "Generated by EternalForge daily capture.",
        "",
    ]
    if not hits_by_topic:
        lines.append("(no topics)")
        lines.append("")
        return "\n".join(lines)
    for topic, hits in hits_by_topic.items():
        lines.append(f"## {topic}")
        lines.append("")
        if not hits:
            lines.append("(no results)")
        else:
            for hit in hits:
                title = hit.title.strip() or "(untitled)"
                snippet = summarize(hit.snippet, 220) if hit.snippet else ""
                if hit.url:
                    lines.append(f"- [{title}]({hit.url})")
                else:
                    lines.append(f"- {title}")
                if snippet:
                    lines.append(f"  {snippet}")
        lines.append("")
    return "\n".join(lines)


def capture(
    root: Path,
    topics: list[str] | None = None,
    adapter: SearchAdapter | None = None,
    max_results: int = 3,
    day: str | None = None,
    journal: Journal | None = None,
) -> CaptureResult:
    """Research each topic and write a daily markdown file under memory/."""
    chosen = [t.strip() for t in (topics or list(DEFAULT_TOPICS)) if t.strip()]
    day_key = day or _utc_day()
    # Validate date-ish keys without being pedantic about calendar correctness.
    try:
        date.fromisoformat(day_key)
    except ValueError as exc:
        raise ValueError(f"day must be YYYY-MM-DD, got {day_key!r}") from exc

    hits_by_topic: dict[str, list[Hit]] = {}
    total = 0
    for topic in chosen:
        hits = search(topic, max_results=max_results, adapter=adapter)
        hits_by_topic[topic] = hits
        total += len(hits)

    markdown = render_digest(day_key, hits_by_topic)
    memory_dir = root / "memory"
    memory_dir.mkdir(parents=True, exist_ok=True)
    path = memory_dir / f"{day_key}.md"
    if path.exists():
        existing = path.read_text(encoding="utf-8")
        path.write_text(existing.rstrip() + "\n\n" + markdown, encoding="utf-8")
    else:
        path.write_text(markdown, encoding="utf-8")

    log = journal or Journal(memory_dir / "journal.jsonl")
    log.append(
        MemoryEntry.now(
            "capture",
            f"Captured {len(chosen)} topic(s) into {path.name}",
            format_hits([h for hits in hits_by_topic.values() for h in hits]),
        )
    )
    return CaptureResult(
        day=day_key,
        path=path,
        topics=chosen,
        hit_count=total,
        markdown=markdown,
        hits_by_topic=hits_by_topic,
    )
