"""MultiAdapter backend list (kept small for GitHub writes)."""
from __future__ import annotations

import importlib

_MULTI: list[tuple[str, str]] = [
    ("research_wiki", "WikipediaAdapter"),
    ("research_wiki", "DuckDuckGoAdapter"),
    ("openlibrary", "OpenLibraryAdapter"),
    ("hackernews", "HackerNewsAdapter"),
    ("arxiv", "ArxivAdapter"),
    ("crossref", "CrossrefAdapter"),
    ("semanticscholar", "SemanticScholarAdapter"),
    ("pubmed", "PubMedAdapter"),
    ("europepmc", "EuropePMCAdapter"),
    ("openalex", "OpenAlexAdapter"),
    ("zenodo", "ZenodoAdapter"),
    ("datacite", "DataCiteAdapter"),
    ("doaj", "DoajAdapter"),
    ("wikidata", "WikidataAdapter"),
    ("openaire", "OpenaireAdapter"),
    ("core", "CoreAdapter"),
    ("s2graph", "S2GraphAdapter"),
    ("unpaywall", "UnpaywallAdapter"),
    ("xrefextra", "XrefExtraAdapter"),
    ("oaextra", "OaExtraAdapter"),
    ("oairextra", "OaireExtraAdapter"),
    ("epmcextra", "EpmcExtraAdapter"),
    ("orcidextra", "OrcidExtraAdapter"),
    ("dcextra", "DataCiteExtraAdapter"),
    ("crfunder", "CrFunderAdapter"),
    ("oafunder", "OaFunderAdapter"),
    ("orcidworks", "OrcidWorksAdapter"),
    ("oatopic", "OaTopicAdapter"),
    ("oaconcept", "OaConceptAdapter"),
    ("oasource", "OaSourceAdapter"),
    ("oapublisher", "OaPublisherAdapter"),
    ("oainstitution", "OaInstitutionAdapter"),
    ("oaauthor", "OaAuthorAdapter"),
    ("oayear", "OaYearAdapter"),
    ("oatype", "OaTypeAdapter"),
    ("oalang", "OaLangAdapter"),
    ("oaostatus", "OaOaStatusAdapter"),
    ("oacountry", "OaCountryAdapter"),
    ("oacontinent", "OaContinentAdapter"),
    ("oasrctype", "OaSrcTypeAdapter"),
    ("oaretracted", "OaRetractedAdapter"),
    ("oaparatext", "OaParatextAdapter"),
    ("oadoi", "OaDoiAdapter"),
    ("oahasoa", "OaHasOaAdapter"),
    ("oahaspmid", "OaHasPmidAdapter"),
    ("oahaspmcid", "OaHasPmcidAdapter"),
    ("oahasisn", "OaHasIssnAdapter"),
    ("oahasorcid", "OaHasOrcidAdapter"),
    ("oahasaffil", "OaHasAffilAdapter"),
    ("oahasrefs", "OaHasRefsAdapter"),
    ("oahasabs", "OaHasAbsAdapter"),
    ("oahaspdf", "OaHasPdfAdapter"),
    ("oahasft", "OaHasFtAdapter"),
    ("oahasoaap", "OaHasOaapAdapter"),
    ("oahasoasub", "OaHasOaSubAdapter"),
    ("oahasoarepo", "OaHasOaRepoAdapter"),
    ("oahasogold", "OaHasOaGoldAdapter"),
    ("oahasoahybrid", "OaHasOaHybridAdapter"),
    ("oahasobronze", "OaHasOaBronzeAdapter"),
    ("oahasogreen", "OaHasOaGreenAdapter"),
    ("oahasodiamond", "OaHasOaDiamondAdapter"),
    ("oaisoa", "OaIsOaAdapter"),
    ("oahasoanyrepo", "OaHasOaAnyRepoAdapter"),
    ("oahasoapub", "OaHasOaPubAdapter"),
    ("oahasoadomain", "OaHasOaDomainAdapter"),
    ("oahasoofile", "OaHasOaFileAdapter"),
    ("oahasoaurl", "OaHasOaUrlAdapter"),
    ("oahasoaver", "OaHasOaVerAdapter"),
    ("oahasoaalic", "OaHasOaLicAdapter"),
    ("oahasoaalicid", "OaHasOaLicIdAdapter"),
    ("oabestlic", "OaBestLicAdapter"),
    ("oabestlicid", "OaBestLicIdAdapter"),
    ("oabestver", "OaBestVerAdapter"),
    ("oabestsrc", "OaBestSrcAdapter"),
    ("oabestsrcid", "OaBestSrcIdAdapter"),
    ("oabestsrctype", "OaBestSrcTypeAdapter"),
    ("oabestissn", "OaBestIssnAdapter"),
    ("oabesthost", "OaBestHostAdapter"),
    ("oabesthoname", "OaBestHoNameAdapter"),
    ("oabestholineage", "OaBestHoLineageAdapter"),
    ("oabestholinames", "OaBestHoLinamesAdapter"),
    ("oabestdoaj", "OaBestDoajAdapter"),
    ("oabestcore", "OaBestCoreAdapter"),
    ("oabestisoa", "OaBestIsOaAdapter"),
    ("oabestissns", "OaBestIssnsAdapter"),
    ("oabestdname", "OaBestDnameAdapter"),
    ("oapridname", "OaPriDnameAdapter"),
    ("oapriissns", "OaPriIssnsAdapter"),
    ("oapriissn", "OaPriIssnAdapter"),
    ("oapriisoa", "OaPriIsOaAdapter"),
    ("oapridoaj", "OaPriDoajAdapter"),
    ("oapricore", "OaPriCoreAdapter"),
    ("oaprihost", "OaPriHostAdapter"),
    ("oaprihoname", "OaPriHoNameAdapter"),
    ("oapriholineage", "OaPriHoLineageAdapter"),
    ("oapriholinames", "OaPriHoLinamesAdapter"),
    ("oaprisrcid", "OaPriSrcIdAdapter"),
    ("oaprisrctype", "OaPriSrcTypeAdapter"),
    ("oapriver", "OaPriVerAdapter"),
    ("oaprilic", "OaPriLicAdapter"),
    ("oaprilicid", "OaPriLicIdAdapter"),
    ("oapriisoaloc", "OaPriIsOaLocAdapter"),
    ("oapripdfurl", "OaPriPdfUrlAdapter"),
    ("oaprilpage", "OaPriLpageAdapter"),
    ("oabestlpage", "OaBestLpageAdapter"),
    ("oabestpdfurl", "OaBestPdfUrlAdapter"),
    ("oabestisoaloc", "OaBestIsOaLocAdapter"),
    ("oalocisoa", "OaLocIsOaAdapter"),
    ("oalocpdfurl", "OaLocPdfUrlAdapter"),
    ("oaloclpage", "OaLocLpageAdapter"),
    ("oalocver", "OaLocVerAdapter"),
    ("oaloclic", "OaLocLicAdapter"),
    ("oaloclicid", "OaLocLicIdAdapter"),
    ("oalocsrcid", "OaLocSrcIdAdapter"),
    ("oalocsrctype", "OaLocSrcTypeAdapter"),
    ("oalocissns", "OaLocIssnsAdapter"),
    ("oalocissn", "OaLocIssnAdapter"),
    ("oalocsrcisoa", "OaLocSrcIsOaAdapter"),
    ("oalocdoaj", "OaLocDoajAdapter"),
    ("oaloccore", "OaLocCoreAdapter"),
    ("oalochost", "OaLocHostAdapter"),
    ("oalochoname", "OaLocHoNameAdapter"),
    ("oalocholineage", "OaLocHoLineageAdapter"),
    ("oalocholinames", "OaLocHoLinamesAdapter"),
    ("oalocdname", "OaLocDnameAdapter"),
    ("oaauthcc", "OaAuthCcAdapter"),
    ("oaauthtype", "OaAuthTypeAdapter"),
    ("oaauthid", "OaAuthIdAdapter"),
    ("oaauthror", "OaAuthRorAdapter"),
    ("oaauthdname", "OaAuthDnameAdapter"),
    ("oaauthlin", "OaAuthLinAdapter"),
    ("oaauthlinnames", "OaAuthLinNamesAdapter"),
    ("oaauthorid", "OaAuthorIdAdapter"),
    ("oaauthororcid", "OaAuthorOrcidAdapter"),
    ("oaauthordname", "OaAuthorDnameAdapter"),
    ("oaauthorcorr", "OaAuthorCorrAdapter"),
    ("oaauthoraffil", "OaAuthorAffilAdapter"),
]


def default_multi_adapters(timeout: float = 8.0):
    adapters = []
    for mod_name, cls_name in _MULTI:
        if mod_name == "openlibrary" and cls_name == "OpenLibraryAdapter":
            from tools.openlibrary import OpenLibraryAdapter
            adapters.append(OpenLibraryAdapter(timeout=timeout))
            continue
        mod = importlib.import_module(f"tools.{mod_name}")
        adapters.append(getattr(mod, cls_name)(timeout=timeout))
    return adapters
